exclude: ['README.md', 'comp90042_2016', 'comp90042_2017', 'comp90042_2018']
timezone: Australia/Eastern
lectures:
# week 1, no workshops
   -
    date: 2018-2-27
    title: Introduction and Preprocessing
    slides: 
      - WSTA_L1a_introduction.pdf
      - WSTA_L1b_preprocessing.pdf
    reading:
      - <a href="https://web.stanford.edu/~jurafsky/slp3/2.pdf">JM3 Ch. 2</a>
    notebook: 
      - WSTA_N1B_preprocessing.ipynb
      - Python-intro.ipynb
      - words
    who: trevor and daniel
    show: 1
   -
    date: 2018-2-28
    title: Text classification
    slides: WSTA_L2_text_classification.pdf
    reading:
      - <a href="https://web.stanford.edu/~jurafsky/slp3/6.pdf">JM3 Ch. 6</a>
      - <a href="https://web.stanford.edu/~jurafsky/slp3/7.pdf">JM3 Ch. 7</a>
    notebook: WSTA_N2_text_classification.ipynb
    who: daniel
    show: 1
# week 2
   -
    date: 2018-3-5
    title: "Workshop on preprocessing and text classification"
    type: workshop
    worksheet: 
        - workshop-02.pdf
        - solutions-02.pdf
    who: tutors
    show: 1
   -
    date: 2018-3-6
    title: Lexical semantics
    slides: WSTA_L3_lexical_semantics.pdf
    reading:
      - <a href="https://web.stanford.edu/~jurafsky/slp3/17.pdf">JM3 Ch. 17</a>
    notebook: WSTA_N3_lexical_semantics.ipynb
    who: daniel
    show: 1
   -
    date: 2018-3-7
    title: Distributional semantics
    slides: WSTA_L4_distributional_semantics.pdf
    reading:
      - <a href="https://web.stanford.edu/~jurafsky/slp3/15.pdf">JM3 Ch. 15</a>
      - <a href="https://web.stanford.edu/~jurafsky/slp3/16.pdf"> JM3 Ch. 16.1 - 16.2 </a>
      - '(Optional) <a href="https://www.jair.org/media/2934/live-2934-4846-jair.pdf">From Frequency to Meaning: Vector Space Models of Semantics</a>'
    notebook: WSTA_N4_distributional_semantics.ipynb 
    who: daniel
    show: 1
# week 3
   -
    date: 2018-3-12
    title: "Workshop on word semantics"
    type: workshop
    worksheet:
        - workshop-03.pdf
        - solutions-03.pdf
    who: tutors
    show: 1
   -
    date: 2018-3-13
    title: Part of Speech Tagging 
    reading: 
     - <a href="https://web.stanford.edu/~jurafsky/slp3/10.pdf">JM3 Ch. 10.1-10.3, 10.7</a>
    slides: WSTA_L5_part_of_speech_tagging.pdf
    notebook: WSTA_N5_part_of_speech_tagging.ipynb
    who: daniel
    show: 1
   -
    date: 2018-3-14
    title: Probabilisitic Sequence Modelling
    slides: WSTA_L6_probabilistic_sequence_models.pdf
    notebook: WSTA_N6_hidden_markov_models.ipynb
    reading:
        - <a href="https://web.stanford.edu/~jurafsky/slp3/9.pdf">JM3 Ch. 9.1, 9.2, 9.4</a>
        - <a href="https://web.stanford.edu/~jurafsky/slp3/10.pdf">JM3 Ch. 10.4</a>
    who: daniel
    show: 1 
# week 4
   -
    date: 2018-3-19
    title: "Workshop on POS tagging and HMMs"
    type: workshop
    worksheet:
        - workshop-04.pdf
        - solutions-04.pdf
    who: tutors
    show: 1
   -
    date: 2018-3-20
    title: Unsupervised Hidden Markov Models
    slides: WSTA_L7_unsupervised_hmms.pdf
    notebook: WSTA_N7_unsupervised_HMMs.ipynb
    reading:
        - <a href="https://web.stanford.edu/~jurafsky/slp3/9.pdf">JM3 Ch. 9.3, 9.5</a>
        - (Optional) <a href="https://ebookcentral.proquest.com/lib/unimelb/reader.action?docID=3339544&ppg=354">MS chapters 9  &amp; 10 </a>
        - (Optional) <a href="http://www.ece.ucsb.edu/Faculty/Rabiner/ece259/Reprints/tutorial%20on%20hmm%20and%20applications.pdf">Rabiner's HMM tutorial</a>
    who: daniel
    show: 1
   -
    date: 2018-3-21
    title: Context-Free Grammars
    slides: WSTA_L8_context-free_grammars.pdf 
    notebook: WSTA_N8_context-free_grammars.ipynb
    reading: 
      - <a href="https://web.stanford.edu/~jurafsky/slp3/11.pdf">JM3 Ch. 11.1-11.5</a>
      - <a href="https://web.stanford.edu/~jurafsky/slp3/12.pdf">JM3 Ch. 12</a>
      - <a href="http://people.umass.edu/nconstan/201/Constituency%20Tests.pdf">syntactic constituency tests</a>
    who: trevor
    show: 1
# week 5
   -
    date: 2018-3-26
    title: Workshop (schedule altered for Good Friday holiday)
    type: workshop
    worksheet: 
        - workshop-05.pdf
    who: tutors
    show: 1
   -
    date: 2018-3-27
    title: Probablisitic Parsing
    slides: WSTA_L9_probabilistic_grammars.pdf
    notebook: WSTA_N9_probabilistic_parsing.ipynb
    reading: <a href="https://web.stanford.edu/~jurafsky/slp3/13.pdf">JM3 Ch. 13-13.6</a>
    who: trevor
    show: 1
   -
    date: 2018-3-28
    title: Dependency parsing
    slides: WSTA_L10_dependency.pdf
    reading: <a href="https://web.stanford.edu/~jurafsky/slp3/14.pdf">JM3 Ch. 14</a>
    who: trevor
    show: 1
# week off
   -
    date: 2018-4-2
    title: "Easter holiday break"
# week 6 
   -
    date: 2018-4-9
    title: Workshop 
    type: workshop
    worksheet: 
       - workshop-06.pdf
    who: tutors
    show: 1
   -
    date: 2018-4-10
    title: Ngram language modelling
    slides: WSTA_L11_n-gram_language_models.pdf
    notebook: WSTA_N11_n-gram_language_models.ipynb
    reading: <a href="https://web.stanford.edu/~jurafsky/slp3/4.pdf"> JM3 Ch. 4 </a>
    who: daniel
    show: 1
   -
    date: 2018-4-10
    title: Deep learning for language models and tagging
    who: trevor
    slides: WSTA_L12_neural_language_models.pdf
    reading: 
        - <a href="https://web.stanford.edu/~jurafsky/slp3/8.pdf"> JM3 Ch. 8 </a>
        - <a href="https://arxiv.org/abs/1703.01619"> Neubig 2017, sections 5-6 </a>
    show: 1
# week 7
   -
    date: 2018-4-16
    title: Workshop 
    type: workshop
    worksheet: 
       - workshop-07.pdf
    who: tutors
    show: 1
   -
    date: 2018-4-17
    title: Information Extraction
    slides: 
    reading: <a href="https://web.stanford.edu/~jurafsky/slp3/21.pdf"> JM3 Ch. 21 </a>
    who: daniel
    slides: WSTA_L13_information_extraction.pdf
    show: 1
   -
    date: 2018-4-18
    title: Question Answering 
    slides:  WSTA_L14_question_answering.pdf
    reading: 
      - <a href="https://web.stanford.edu/~jurafsky/slp3/28.pdf"> JM3 Ch. 28 </a>
    who: tim
    show: 1
# week 8
   -
    date: 2018-4-23
    title: Workshop
    type: workshop
    worksheet:
        - workshop-08.pdf
    who: tutors
    show: 1
   -
    date: 2018-4-24
    title: Topic Models
    slides: 
    reading: 
    who: daniel
    show: 0
   -
    date: 2018-4-25
    title: "ANZAC day holiday"
# week 9
   -
    date: 2018-4-30
    title: "Workshop"
    type: workshop
    worksheet: 
    who: tutors
    show: 0
   -
    date: 2018-5-1
    title: Information Retrieval -- boolean search and the vector space model 
    slides: 
    notebook: 
    reading:
        - <a href="http://nlp.stanford.edu/IR-book/pdf/01bool.pdf">IIR Chapter 1 (1.1-1.3)</a>
        - <a href="http://nlp.stanford.edu/IR-book/pdf/06vect.pdf">IIR Chapter 6 (6.2-6.4.2)</a>
    who: trevor
    show: 0
   -
    date: 2018-5-2
    title: Indexing and querying in the vector space model, evaluation
    slides: 
    reading:
        - <a href="http://nlp.stanford.edu/IR-book/pdf/07system.pdf">IIR Chapter 7 (7.1)</a>
        - <a href="http://nlp.stanford.edu/IR-book/pdf/08eval.pdf">IIR Chapter 8</a>
    who: trevor
    show: 0
# week 10
   -
    date: 2018-5-7
    title: Workshop 
    type: workshop
    worksheet: 
    who: tutors
    show: 0
   -
    date: 2018-5-8
    title: "Index and vocabulary compression"
    slides: 
    reading:
        - <a href="http://nlp.stanford.edu/IR-book/pdf/05comp.pdf">IIR Chapter 5 </a>
        - see also papers referenced in slides
    who: matthias  
    show: 0
   -
    date: 2018-5-9
    title: "Efficient query processing"
    slides:
    reading:
        - <a href="http://nlp.stanford.edu/IR-book/pdf/05comp.pdf">IIR Chapter 5 </a>
        - see also papers referenced in slides
    who: matthias  
    show: 0
# week 11
   -
    date: 2018-5-14
    title: Workshop 
    type: workshop
    worksheet: 
    who: tutors
    show: 0
   -
    date: 2018-5-15
    title: "The Web as a Graph -- Page-rank and HITS"
    slides: 
    reading:
        - <a href="http://nlp.stanford.edu/IR-book/pdf/21link.pdf">IIR Chapter 21</a>
        - <a href="http://nlp.stanford.edu/IR-book/pdf/18lsi.pdf">IIR Chapter 18 (Eigen decomposition review)</a>
    who: trevor  
    show: 0
   -
    date: 2018-5-16
    title: Machine Translation, word based models 
    slides: 
    notebook:
    who: trevor
    show: 0
    reading:
        - JM2 Chapter 25, 25.4-25.6
        - '<a href="https://www-cambridge-org.ezp.lib.unimelb.edu.au/core/services/aop-cambridge-core/content/view/6F03C4290D7E98278BB2F6A8CA8F6D1F/9780511815829c4_p81-126_CBO.pdf/wordbased_models.pdf">Koehn09 Chapter 4</a>, 4.1-4.3'
# week 12
   -
    date: 2018-5-21
    title: "Workshop"
    type: workshop
    worksheet: 
        - workshop-12.pdf
        - solutions-12.pdf
    who: tutors
    show: 0
   -
    date: 2018-5-22
    title: Machine translation, phrase based translation and neural encoder-decoder
    slides: 
    who: trevor
    show: 0
    reading:
        - 'JM2 Chapter 25: 25.7-25.9'
        - '<a href="https://www-cambridge-org.ezp.lib.unimelb.edu.au/core/services/aop-cambridge-core/content/view/0B9EC28212FB7D15563B8F9B85A2870B/9780511815829c5_p127-154_CBO.pdf/phrasebased_models.pdf">Koehn09 Chapter 5</a>, 5.1-5.2'
        - '<a href="https://www-cambridge-org.ezp.lib.unimelb.edu.au/core/services/aop-cambridge-core/content/view/50D47709AF26FAB89975797E5E5B6C12/9780511815829c6_p155-180_CBO.pdf/decoding.pdf">Koehn09 Chapter 6</a>, 6.1-6.2'
        - '(opt.) <a href="https://arxiv.org/abs/1703.01619">Neural Machine Translation and Sequence-to-sequence Models: A Tutorial, Neubig 2017</a>'
   -
    date: 2018-5-23
    title: Subject review
    slides: WSTA_L23_review.pdf
    who: trevor and daniel
    show: 0
